# Generated by Django 3.0.5 on 2020-05-08 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200508_2117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
